// Code generated by goctl. DO NOT EDIT.
// Source: message.proto

package server

import (
	"context"

	"zerorpc_demo/message/internal/logic"
	"zerorpc_demo/message/internal/svc"
	"zerorpc_demo/message/rpc/types/message"
)

type MessageServer struct {
	svcCtx *svc.ServiceContext
	message.UnimplementedMessageServer
}

func NewMessageServer(svcCtx *svc.ServiceContext) *MessageServer {
	return &MessageServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServer) SendMessage(ctx context.Context, in *message.SendRequest) (*message.SendResponse, error) {
	l := logic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}
