// Code generated by goctl. DO NOT EDIT.
// Source: email.proto

package emailclient

import (
	"context"

	"zerorpc_demo/email/rpc/types/email"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UserEmailRequest  = email.UserEmailRequest
	UserEmailResponse = email.UserEmailResponse

	Email interface {
		SendEmail(ctx context.Context, in *UserEmailRequest, opts ...grpc.CallOption) (*UserEmailResponse, error)
	}

	defaultEmail struct {
		cli zrpc.Client
	}
)

func NewEmail(cli zrpc.Client) Email {
	return &defaultEmail{
		cli: cli,
	}
}

func (m *defaultEmail) SendEmail(ctx context.Context, in *UserEmailRequest, opts ...grpc.CallOption) (*UserEmailResponse, error) {
	client := email.NewEmailClient(m.cli.Conn())
	return client.SendEmail(ctx, in, opts...)
}
