// Code generated by goctl. DO NOT EDIT.
// Source: email.proto

package server

import (
	"context"

	"zerorpc_demo/email/internal/logic"
	"zerorpc_demo/email/internal/svc"
	"zerorpc_demo/email/rpc/types/email"
)

type EmailServer struct {
	svcCtx *svc.ServiceContext
	email.UnimplementedEmailServer
}

func NewEmailServer(svcCtx *svc.ServiceContext) *EmailServer {
	return &EmailServer{
		svcCtx: svcCtx,
	}
}

func (s *EmailServer) SendEmail(ctx context.Context, in *email.UserEmailRequest) (*email.UserEmailResponse, error) {
	l := logic.NewSendEmailLogic(ctx, s.svcCtx)
	return l.SendEmail(in)
}
