// Code generated by goctl. DO NOT EDIT.
// Source: domain.proto

package server

import (
	"context"

	"zerorpc_demo/domain/internal/logic"
	"zerorpc_demo/domain/internal/svc"
	"zerorpc_demo/domain/rpc/types/domain"
)

type DomainServer struct {
	svcCtx *svc.ServiceContext
	domain.UnimplementedDomainServer
}

func NewDomainServer(svcCtx *svc.ServiceContext) *DomainServer {
	return &DomainServer{
		svcCtx: svcCtx,
	}
}

func (s *DomainServer) GetDomainAll(ctx context.Context, in *domain.DomainReq) (*domain.DomainInfoResp, error) {
	l := logic.NewGetDomainAllLogic(ctx, s.svcCtx)
	return l.GetDomainAll(in)
}
