// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userclient

import (
	"context"

	"zerorpc_demo/user/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IdRequest    = user.IdRequest
	ResponseMsg  = user.ResponseMsg
	UserInfo     = user.UserInfo
	UserLogin    = user.UserLogin
	UserResponse = user.UserResponse

	User interface {
		Login(ctx context.Context, in *UserLogin, opts ...grpc.CallOption) (*UserResponse, error)
		GetUserInfo(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserResponse, error)
		UpdateUserInfo(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*ResponseMsg, error)
		DeleteUser(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*ResponseMsg, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Login(ctx context.Context, in *UserLogin, opts ...grpc.CallOption) (*UserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) GetUserInfo(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUser) UpdateUserInfo(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*ResponseMsg, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

func (m *defaultUser) DeleteUser(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*ResponseMsg, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}
